services:
  slskd:
    image: slskd/slskd
    container_name: slskd
    ports:
      - "5030:5030"
      # - "5031:5031"
      # - "50300:50300"
    environment:
      - SLSKD_REMOTE_CONFIGURATION=true
    volumes:
      - ./data:/app
      - /mnt/bendo4/SHARE/slskd:/downloads
    restart: unless-stopped
    labels:
      tsdproxy.enable: "true"